apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/deployment.cancelled: "2"
  creationTimestamp: null
  labels:
    run: git
  name: git
spec:
  replicas: 1
  selector:
    run: git
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: git
    spec:
      containers:
      - env:
        - name: DEBUG_ENTRYPOINT
          value: "1"
        - name: DEBUG
          value: "true"
        - name: DB_HOST
          value: 172.30.10.109
        - name: DB_ADAPTER
          value: postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: gitlab
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: AsiainfoLDP2016
        - name: REDIS_HOST
          value: 172.30.239.214
        - name: REDIS_PORT
          value: "6379"
        - name: GITLAB_HOST
          value: git.app-test.dataos.io
        - name: GITLAB_HTTPS
          value: "false"
        - name: GITLAB_SSH_PORT
          value: "22"
        - name: OAUTH_CAS3_SERVER
          value: http://10.1.235.245:14125
        - name: OAUTH_CAS3_LOGIN_URL
          value: /citic-uac/login
        - name: OAUTH_CAS3_LOGOUT_URL
          value: /citic-uac/logout
        - name: GITLAB_SECRETS_DB_KEY_BASE
          value: yaju-and-random-alpha-numeric-string
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          value: yaju-and-random-alpha-numeric-string
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          value: yaju-and-random-alpha-numeric-string
        - name: OAUTH_CAS3_VALIDATE_URL
          value: /citic-uac/p3/serviceValidate
        image: registry.dataos.io/liuliu/sameersbn-gitlab:8.14.0
        imagePullPolicy: Always
        name: git
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /home/git/data
          name: volume-yt62j
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: volume-yt62j
  test: false
  triggers:
  - type: ConfigChange
status: {}
