apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    run: ldap
  name: ldap
spec:
  replicas: 1
  selector:
    run: ldap
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: ldap
    spec:
      containers:
      - env:
        - name: OPENLDAP_ROOT_PASSWORD
          value: password
        - name: OPENLDAP_ROOT_DN_RREFIX
          value: cn=admin
        - name: OPENLDAP_ROOT_DN_SUFFIX
          value: dc=openstack
        - name: dc
          value: org
        image: index.alauda.cn/asiainfoldp/docker-openldap
        imagePullPolicy: Always
        name: ldap
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/ldap
          name: pvc-var-lib-ldap
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pvc-var-lib-ldap
        emptyDir:
  test: false
  triggers:
  - type: ConfigChange
status: {}
