apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ldap
  name: ldap
spec:
  ports:
  - port: 389
    protocol: TCP
    targetPort: 389
  selector:
    run: ldap
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
