apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    run: postgresql
  name: postgresql
spec:
  replicas: 1
  selector:
    run: postgresql
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: postgresql
    spec:
      containers:
      - env:
        - name: DB_NAME
          value: gitlab
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          value: AsiainfoLDP2016
        - name: DB_ADAPTER
          value: postgresql
        - name: DB_EXTENSION
          value: pg_trgm
        image: docker.io/sameersbn/postgresql:9.5-3
        imagePullPolicy: IfNotPresent
        name: postgresql
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
status: {}
