apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: git
  name: ssh-git
spec:
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    run: git
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
